import { ViewStyle, TextStyle } from 'react-native';
import { Colors, Radius, Spacing } from '@/constants/theme';

export const datePickerStyles: Record<string, ViewStyle | TextStyle> = {
  header: {
    marginBottom: Spacing.xs,
    paddingHorizontal: Spacing.xs,
  },
  month_selector_label: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.light.text,
  },
  year_selector_label: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.light.text,
  },
  button_prev: {
    padding: 6,
    borderRadius: Radius.full,
    backgroundColor: Colors.light.surfaceMuted,
  },
  button_next: {
    padding: 6,
    borderRadius: Radius.full,
    backgroundColor: Colors.light.surfaceMuted,
  },
  weekdays: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.borderSubtle,
    paddingBottom: 8,
    marginBottom: 6,
  },
  weekday_label: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.light.textMuted,
    textTransform: 'uppercase',
  },
  day_cell: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  day: {
    width: 38,
    height: 38,
    minWidth: 38,
    minHeight: 38,
    maxWidth: 38,
    maxHeight: 38,
    aspectRatio: 1,
    borderRadius: 19,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 0,
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: 38,
    overflow: 'hidden',
  },
  day_label: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.light.text,
    textAlign: 'center',
    includeFontPadding: false,
  },
  selected: {
    backgroundColor: Colors.light.brand,
    borderRadius: 19,
    width: 38,
    height: 38,
    minWidth: 38,
    minHeight: 38,
    maxWidth: 38,
    maxHeight: 38,
    aspectRatio: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 0,
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: 38,
    borderWidth: 0,
    overflow: 'hidden',
  },
  selected_label: {
    color: '#FFFFFF',
    fontWeight: '700',
    textAlign: 'center',
    includeFontPadding: false,
  },
  today: {
    borderWidth: 1.5,
    borderColor: Colors.light.brand,
    borderRadius: 19,
    width: 38,
    height: 38,
    minWidth: 38,
    minHeight: 38,
    maxWidth: 38,
    maxHeight: 38,
    aspectRatio: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 0,
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: 38,
    overflow: 'hidden',
  },
  today_label: {
    color: Colors.light.brand,
    fontWeight: '700',
    textAlign: 'center',
    includeFontPadding: false,
  },
  outside_label: {
    color: Colors.light.textMuted,
    opacity: 0.35,
  },
  disabled_label: {
    color: Colors.light.textMuted,
    opacity: 0.25,
  },
  month: {
    borderRadius: Radius.md,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  month_label: {
    fontSize: 14,
    color: Colors.light.text,
  },
  selected_month: {
    backgroundColor: Colors.light.brand,
    borderRadius: Radius.md,
  },
  selected_month_label: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  year: {
    borderRadius: Radius.md,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  year_label: {
    fontSize: 14,
    color: Colors.light.text,
  },
  selected_year: {
    backgroundColor: Colors.light.brand,
    borderRadius: Radius.md,
  },
  selected_year_label: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
};
